import { create } from 'zustand';

const translations = {
  en: {
    welcome: "Welcome",
    home: "Home",
    orders: "Orders",
    about: "About",
    profile: "Profile",
    search: "What would you like to order today?",
    add: "Add",
    added: "Added",
    checkout: "Checkout",
    total: "Total",
    cart_empty: "Your cart is empty",
    explore: "Explore Festival Special",
    preferences: "Preferences",
    language: "Language",
    dark_mode: "Dark Mode",
    my_orders: "My Orders",
    rewards: "Rewards & Coupons",
    points: "Tap to view your points!",
    logout: "Secure Sign Out",
    admin_panel: "Admin Panel",
    manage_products: "Manage Products",
    add_product: "Add Product",
    edit_product: "Edit Product",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    name: "Name",
    price: "Price",
    stock: "Stock",
    category: "Category",
    unit: "Unit",
    claim: "Claim",
    done: "Done",
    complete_profile: "Complete Profile",
    add_email: "Add your email & photo",
    first_order: "First Order",
    place_order: "Place your first order",
    review: "Leave a Review",
    share: "Share App",
    invite_friends: "Invite 5 friends",
    scan_qr: "Scan QR",
    store_visit: "Visit our store",
    coupon: "Coupon",
    off: "OFF",
    use_code: "Use Code:",
    valid_until: "Valid until:",
    account_details: "Account Details",
    phone_number: "Phone Number",
    delivery_address: "Delivery Address",
    edit: "Edit",
    save_changes: "Save Changes",
    name_placeholder: "Enter full name",
    email_placeholder: "Enter email address",
    address_placeholder: "Enter delivery address",
    change_photo: "Change Photo",
    progress_to_coupon: "Progress to ₹50 Coupon",
    rewards_info: "Earn 50 points on your first order. 100 points for completing your profile!",
    earn_more_points: "Earn More Points",
    rate_delivery: "Rate a Delivery",
    give_feedback: "Give feedback on your recent order",
    refer_friend: "Refer a Friend",
    share_code: "Share your referral code with a friend",
    my_rewards: "My Rewards",
    status: "Status",
    recent_orders: "Recent Orders",
    only: "Only",
    left: "left",
    out_of_stock: "Out of Stock"
  },
  mr: {
    welcome: "स्वागत आहे",
    home: "मुख्य पान",
    orders: "ऑर्डर्स",
    about: "आमच्याबद्दल",
    profile: "प्रोफाईल",
    search: "आज तुम्हाला काय ऑर्डर करायला आवडेल?",
    add: "जोडा",
    added: "जोडले",
    checkout: "चेकआउट",
    total: "एकूण",
    cart_empty: "तुमची कार्ट रिकामी आहे",
    explore: "सण विशेष एक्सप्लोर करा",
    preferences: "पसंती",
    language: "भाषा",
    dark_mode: "डार्क मोड",
    my_orders: "माझ्या ऑर्डर्स",
    rewards: "बक्षिसे आणि कूपन",
    points: "तुमचे पॉइंट्स पाहण्यासाठी टॅप करा!",
    logout: "सुरक्षित साइन आउट",
    admin_panel: "अॅडमिन पॅनेल",
    manage_products: "उत्पादने व्यवस्थापित करा",
    add_product: "उत्पादन जोडा",
    edit_product: "उत्पादन संपादित करा",
    save: "जतन करा",
    cancel: "रद्द करा",
    delete: "हटवा",
    name: "नाव",
    price: "किंमत",
    stock: "स्टॉक",
    category: "श्रेणी",
    unit: "एकक",
    claim: "मिळवा",
    done: "पूर्ण",
    complete_profile: "प्रोफाईल पूर्ण करा",
    add_email: "तुमचा ईमेल आणि फोटो जोडा",
    first_order: "पहिली ऑर्डर",
    place_order: "तुमची पहिली ऑर्डर द्या",
    review: "रिव्ह्यू द्या",
    share: "अॅप शेअर करा",
    invite_friends: "५ मित्रांना आमंत्रित करा",
    scan_qr: "QR स्कॅन करा",
    store_visit: "आमच्या दुकानाला भेट द्या",
    coupon: "कूपन",
    off: "सूट",
    use_code: "कोड वापरा:",
    valid_until: "पर्यंत वैध:",
    account_details: "खात्याचे तपशील",
    phone_number: "फोन नंबर",
    delivery_address: "वितरणाचा पत्ता",
    edit: "संपादित करा",
    save_changes: "बदल जतन करा",
    name_placeholder: "पूर्ण नाव प्रविष्ट करा",
    email_placeholder: "ईमेल पत्ता प्रविष्ट करा",
    address_placeholder: "वितरणाचा पत्ता प्रविष्ट करा",
    change_photo: "फोटो बदला",
    progress_to_coupon: "₹50 कूपनसाठी प्रगती",
    rewards_info: "तुमच्या पहिल्या ऑर्डरवर ५० पॉइंट्स मिळवा. प्रोफाईल पूर्ण केल्यावर १०० पॉइंट्स!",
    earn_more_points: "आणखी पॉइंट्स मिळवा",
    rate_delivery: "वितरणाचे रेटिंग द्या",
    give_feedback: "तुमच्या अलीकडील ऑर्डरवर प्रतिक्रिया द्या",
    refer_friend: "मित्राला संदर्भ द्या",
    share_code: "तुमचा रेफरल कोड मित्रासोबत शेअर करा",
    my_rewards: "माझे बक्षिसे",
    status: "स्थिती",
    recent_orders: "अलीकडील ऑर्डर्स",
    only: "फक्त",
    left: "शिल्लक",
    out_of_stock: "स्टॉक संपला"
  }
};

const useLanguageStore = create((set, get) => ({
  lang: 'en',
  setLang: (lang) => set({ lang }),
  t: (key) => {
    const { lang } = get();
    return translations[lang][key] || key;
  }
}));

export default useLanguageStore;
